// zh-CN Simplified Chinese
export const zhCN = {
  common: { loading: '加载中...', error: '错误', cancel: '取消', save: '保存', confirm: '确认', done: '完成', back: '返回', retry: '重试', ok: '好的', yes: '是', no: '否', coins: '金币', free: '免费', unlimited: '无限' },
  tabs: { home: '首页', earn: '赚取', boost: '推广', profile: '我的', admin: '管理' },
  splash: { tagline: '共同成长' },
  login: { title: 'Subs Share', tagline: '订阅赚取金币。\n花费金币增长。', feature1: '通过订阅频道赚取金币', feature2: '经YouTube验证——无虚假任务', feature3: '花费金币获取真实订阅者', welcomeBonus: '🎁 免费获得50枚金币！', continueWithGoogle: '使用Google继续', terms: '我们请求只读YouTube访问权限以验证您的订阅和点赞。', signInFailed: '登录失败', noToken: '未收到Google令牌', tryAgain: '请重试' },
  home: { greeting: '你好 👋', balance: '您的余额', coinHint: '10金币 = 1订阅者', campaigns: '活动', pendingSubs: '待处理订阅者', completed: '已完成', quickActions: '快捷操作', earnCoins: '赚取金币', getSubs: '获取订阅者', myChannel: '我的频道', activeCampaign: '个活动进行中', activeCampaigns: '个活动进行中', subsPending: '订阅者等待中', recentActivity: '最近活动', noTransactions: '暂无交易' },
  earn: { title: '赚取金币', subtitle: '完成任务 · 验证 · 领取金币', banner: '🔒 订阅和点赞由YouTube验证。撤销后将追回金币并可能被封禁。', tierFeatured: '⭐ 精选', tierPremium: '💎 高级', tierCommunity: '📋 社区', noTasks: '暂无任务', noTasksSubtitle: '请稍后查看——新活动定期添加', alreadyDone: '✓ 已完成', slotsLeft: '个名额剩余', verifying: 'YouTube验证中...', verifyClaim: '验证并领取', pleaseWait: '请稍候...', readyToVerify: '✅ 准备验证！', inProgress: '进行中', keepActive: '计时器运行时请保持操作', tapToVerify: '点击下方——我们将通过YouTube验证。', secondsRemaining: '秒剩余', commentBonus: '💬 已评论？您将自动获得+4金币！', warningModal: '⚠️ 领取后撤销{{action}}将导致金币被追回。', subscription: '订阅', like: '点赞', coinsEarned: '🎉 金币已获得！', balance: '余额', commentBonusEarned: '💬 评论奖励', noCommentDetected: '（未检测到评论——仅点赞奖励）', notDetectedYet: '尚未检测到', reconnectNeeded: '需要重新连接', reconnectMessage: '请退出并重新登录以授予YouTube访问权限。', tryAgainMessage: '验证繁忙。稍等片刻再点击领取。', accountSuspended: '账号已封禁', slotTaken: '名额已被占用', slotTakenMessage: '有人刚占了最后一个名额。请尝试其他任务！', campaignPaused: '活动已暂停', campaignPausedMessage: '此活动已被所有者暂停。请尝试其他任务。', campaignCancelled: '活动已取消', campaignCancelledMessage: '此活动已取消。请尝试其他任务。' },
  taskTypes: { subscribe: '订阅', like: '点赞视频', like_comment: '点赞+评论', subscribe_like: '订阅+点赞', watch: '观看视频' },
  transactions: { earned: '已赚取', spent: '已花费', bonus: '奖励' },
  language: { title: '语言', select: '选择语言', auto: '自动（系统）', changed: '语言已更改', changedMsg: '应用语言已更新。' },
};

// zh-TW Traditional Chinese
export const zhTW = {
  common: { loading: '載入中...', error: '錯誤', cancel: '取消', save: '儲存', confirm: '確認', done: '完成', back: '返回', retry: '重試', ok: '好的', yes: '是', no: '否', coins: '金幣', free: '免費', unlimited: '無限制' },
  tabs: { home: '首頁', earn: '賺取', boost: '推廣', profile: '我的', admin: '管理' },
  splash: { tagline: '共同成長' },
  login: { title: 'Subs Share', tagline: '訂閱賺取金幣。\n花費金幣成長。', feature1: '透過訂閱頻道賺取金幣', feature2: '經YouTube驗證——無虛假任務', feature3: '花費金幣獲取真實訂閱者', welcomeBonus: '🎁 免費獲得50枚金幣！', continueWithGoogle: '使用Google繼續', terms: '我們請求唯讀YouTube存取權限以驗證您的訂閱和按讚。', signInFailed: '登入失敗', noToken: '未收到Google令牌', tryAgain: '請重試' },
  home: { greeting: '你好 👋', balance: '您的餘額', coinHint: '10金幣 = 1訂閱者', campaigns: '活動', pendingSubs: '待處理訂閱者', completed: '已完成', quickActions: '快捷操作', earnCoins: '賺取金幣', getSubs: '獲取訂閱者', myChannel: '我的頻道', activeCampaign: '個活動進行中', activeCampaigns: '個活動進行中', subsPending: '訂閱者等待中', recentActivity: '最近活動', noTransactions: '暫無交易' },
  earn: { title: '賺取金幣', subtitle: '完成任務 · 驗證 · 領取金幣', banner: '🔒 訂閱和按讚由YouTube驗證。', tierFeatured: '⭐ 精選', tierPremium: '💎 高級', tierCommunity: '📋 社群', noTasks: '暫無任務', noTasksSubtitle: '請稍後查看', alreadyDone: '✓ 已完成', slotsLeft: '個名額剩餘', verifying: 'YouTube驗證中...', verifyClaim: '驗證並領取', pleaseWait: '請稍候...', readyToVerify: '✅ 準備驗證！', inProgress: '進行中', keepActive: '計時器運行時請保持操作', tapToVerify: '點擊下方——我們將透過YouTube驗證。', secondsRemaining: '秒剩餘', commentBonus: '💬 已留言？您將自動獲得+4金幣！', warningModal: '⚠️ 領取後撤銷{{action}}將導致金幣被追回。', subscription: '訂閱', like: '按讚', coinsEarned: '🎉 金幣已獲得！', balance: '餘額', commentBonusEarned: '💬 留言獎勵', noCommentDetected: '（未偵測到留言——僅按讚獎勵）', notDetectedYet: '尚未偵測到', reconnectNeeded: '需要重新連線', reconnectMessage: '請登出並重新登入以授予YouTube存取權限。', tryAgainMessage: '驗證繁忙。請稍後再試。', accountSuspended: '帳號已封禁', slotTaken: '名額已被佔用', slotTakenMessage: '有人剛佔了最後一個名額。請嘗試其他任務！', campaignPaused: '活動已暫停', campaignPausedMessage: '此活動已被暫停。', campaignCancelled: '活動已取消', campaignCancelledMessage: '此活動已取消。' },
  taskTypes: { subscribe: '訂閱', like: '按讚影片', like_comment: '按讚+留言', subscribe_like: '訂閱+按讚', watch: '觀看影片' },
  transactions: { earned: '已賺取', spent: '已花費', bonus: '獎勵' },
  language: { title: '語言', select: '選擇語言', auto: '自動（系統）', changed: '語言已更改', changedMsg: '應用程式語言已更新。' },
};

// Bengali
export const bn = {
  common: { loading: 'লোড হচ্ছে...', error: 'ত্রুটি', cancel: 'বাতিল', save: 'সংরক্ষণ', confirm: 'নিশ্চিত করুন', done: 'সম্পন্ন', back: 'পিছনে', retry: 'আবার চেষ্টা করুন', ok: 'ঠিক আছে', yes: 'হ্যাঁ', no: 'না', coins: 'কয়েন', free: 'বিনামূল্যে', unlimited: 'সীমাহীন' },
  tabs: { home: 'হোম', earn: 'উপার্জন', boost: 'বুস্ট', profile: 'প্রোফাইল', admin: 'অ্যাডমিন' },
  splash: { tagline: 'একসাথে বড় হই' },
  login: { title: 'Subs Share', tagline: 'উপার্জনের জন্য সাবস্ক্রাইব করুন।\nবড় হতে ব্যয় করুন।', feature1: 'চ্যানেল সাবস্ক্রাইব করে কয়েন উপার্জন করুন', feature2: 'YouTube দ্বারা যাচাইকৃত — কোনো নকল কাজ নেই', feature3: 'প্রকৃত সাবস্ক্রাইবার পেতে কয়েন ব্যয় করুন', welcomeBonus: '🎁 ৫০ বিনামূল্যে কয়েন দিয়ে শুরু করুন!', continueWithGoogle: 'Google দিয়ে চালিয়ে যান', terms: 'আপনার সাবস্ক্রিপশন ও লাইক যাচাই করতে আমরা শুধুমাত্র পড়ার YouTube অ্যাক্সেস চাই।', signInFailed: 'সাইন ইন ব্যর্থ', noToken: 'Google থেকে কোনো টোকেন পাওয়া যায়নি', tryAgain: 'অনুগ্রহ করে আবার চেষ্টা করুন' },
  home: { greeting: 'শুভ দিন 👋', balance: 'আপনার ব্যালেন্স', coinHint: '১০ কয়েন = ১ সাবস্ক্রাইবার', campaigns: 'প্রচারণা', pendingSubs: 'অপেক্ষমাণ সাবস্ক্রাইবার', completed: 'সম্পন্ন', quickActions: 'দ্রুত ক্রিয়া', earnCoins: 'কয়েন উপার্জন', getSubs: 'সাবস্ক্রাইবার পান', myChannel: 'আমার চ্যানেল', activeCampaign: 'সক্রিয় প্রচারণা', activeCampaigns: 'সক্রিয় প্রচারণা', subsPending: 'সাবস্ক্রাইবার অপেক্ষমাণ', recentActivity: 'সাম্প্রতিক কার্যকলাপ', noTransactions: 'এখনো কোনো লেনদেন নেই' },
  earn: { title: 'কয়েন উপার্জন করুন', subtitle: 'কাজ · যাচাইকৃত · কয়েন দাবি করুন', banner: '🔒 সাবস্ক্রিপশন ও লাইক YouTube দ্বারা যাচাই করা হয়।', tierFeatured: '⭐ বৈশিষ্ট্যযুক্ত', tierPremium: '💎 প্রিমিয়াম', tierCommunity: '📋 সম্প্রদায়', noTasks: 'এখনো কোনো কাজ নেই', noTasksSubtitle: 'শীঘ্রই চেক করুন', alreadyDone: '✓ সম্পন্ন', slotsLeft: 'স্লট বাকি', verifying: 'YouTube এর সাথে যাচাই হচ্ছে...', verifyClaim: 'যাচাই করুন ও দাবি করুন', pleaseWait: 'অনুগ্রহ করে অপেক্ষা করুন...', readyToVerify: '✅ যাচাইয়ের জন্য প্রস্তুত!', inProgress: 'চলছে', keepActive: 'টাইমার চলার সময় কার্যক্রম চালু রাখুন', tapToVerify: 'নিচে ট্যাপ করুন — আমরা YouTube দিয়ে যাচাই করব।', secondsRemaining: 'সেকেন্ড বাকি', commentBonus: '💬 মন্তব্য করেছেন? স্বয়ংক্রিয়ভাবে +৪ কয়েন পাবেন!', warningModal: '⚠️ দাবির পরে {{action}} সরালে কয়েন ফিরিয়ে নেওয়া হবে।', subscription: 'সাবস্ক্রিপশন', like: 'লাইক', coinsEarned: '🎉 কয়েন উপার্জিত!', balance: 'ব্যালেন্স', commentBonusEarned: '💬 মন্তব্য বোনাস', noCommentDetected: '(কোনো মন্তব্য পাওয়া যায়নি — শুধু লাইক পুরস্কার)', notDetectedYet: 'এখনো সনাক্ত হয়নি', reconnectNeeded: 'পুনরায় সংযোগ প্রয়োজন', reconnectMessage: 'YouTube অ্যাক্সেস দিতে সাইন আউট করে আবার সাইন ইন করুন।', tryAgainMessage: 'যাচাই ব্যস্ত। একটু অপেক্ষা করে আবার দাবি করুন।', accountSuspended: 'অ্যাকাউন্ট স্থগিত', slotTaken: 'স্লট নেওয়া হয়েছে', slotTakenMessage: 'কেউ শেষ স্লটটি নিয়ে নিয়েছে। অন্য কাজ চেষ্টা করুন!', campaignPaused: 'প্রচারণা বিরতিতে', campaignPausedMessage: 'এই প্রচারণা মালিক বিরতি দিয়েছেন।', campaignCancelled: 'প্রচারণা বাতিল', campaignCancelledMessage: 'এই প্রচারণা বাতিল করা হয়েছে।' },
  taskTypes: { subscribe: 'সাবস্ক্রাইব করুন', like: 'ভিডিও লাইক করুন', like_comment: 'লাইক + মন্তব্য', subscribe_like: 'সাবস্ক্রাইব + লাইক', watch: 'ভিডিও দেখুন' },
  transactions: { earned: 'উপার্জিত', spent: 'ব্যয়িত', bonus: 'বোনাস' },
  language: { title: 'ভাষা', select: 'ভাষা নির্বাচন করুন', auto: 'স্বয়ংক্রিয় (সিস্টেম)', changed: 'ভাষা পরিবর্তিত', changedMsg: 'অ্যাপের ভাষা আপডেট করা হয়েছে।' },
};

// Japanese
export const ja = {
  common: { loading: '読み込み中...', error: 'エラー', cancel: 'キャンセル', save: '保存', confirm: '確認', done: '完了', back: '戻る', retry: '再試行', ok: 'OK', yes: 'はい', no: 'いいえ', coins: 'コイン', free: '無料', unlimited: '無制限' },
  tabs: { home: 'ホーム', earn: '稼ぐ', boost: 'ブースト', profile: 'プロフィール', admin: '管理' },
  splash: { tagline: '一緒に成長しよう' },
  login: { title: 'Subs Share', tagline: '登録して稼ごう。\n使って成長しよう。', feature1: 'チャンネル登録でコインを獲得', feature2: 'YouTubeで確認済み — 偽タスクなし', feature3: 'コインを使って本物のチャンネル登録者を獲得', welcomeBonus: '🎁 50コイン無料でスタート！', continueWithGoogle: 'Googleで続ける', terms: '登録とイイネの確認のため、読み取り専用のYouTubeアクセスをリクエストします。', signInFailed: 'サインイン失敗', noToken: 'Googleからトークンを受信できませんでした', tryAgain: 'もう一度お試しください' },
  home: { greeting: 'こんにちは 👋', balance: 'あなたの残高', coinHint: '10コイン = 1登録者', campaigns: 'キャンペーン', pendingSubs: '保留中の登録者', completed: '完了', quickActions: 'クイックアクション', earnCoins: 'コインを稼ぐ', getSubs: '登録者を獲得', myChannel: '自分のチャンネル', activeCampaign: 'つの進行中キャンペーン', activeCampaigns: 'つの進行中キャンペーン', subsPending: '人の登録者が保留中', recentActivity: '最近のアクティビティ', noTransactions: 'まだ取引がありません' },
  earn: { title: 'コインを稼ぐ', subtitle: 'タスク完了 · 確認 · コインを受け取る', banner: '🔒 登録とイイネはYouTubeで確認されます。', tierFeatured: '⭐ おすすめ', tierPremium: '💎 プレミアム', tierCommunity: '📋 コミュニティ', noTasks: 'まだタスクがありません', noTasksSubtitle: 'また後で確認してください', alreadyDone: '✓ 完了', slotsLeft: '枠残り', verifying: 'YouTubeで確認中...', verifyClaim: '確認して受け取る', pleaseWait: 'お待ちください...', readyToVerify: '✅ 確認準備完了！', inProgress: '進行中', keepActive: 'タイマー中はアクションを維持してください', tapToVerify: '下をタップ — YouTubeで確認します。', secondsRemaining: '秒残り', commentBonus: '💬 コメントしましたか？自動的に+4コインが付与されます！', warningModal: '⚠️ 受け取り後に{{action}}を取り消すとコインが回収されます。', subscription: '登録', like: 'イイネ', coinsEarned: '🎉 コインを獲得！', balance: '残高', commentBonusEarned: '💬 コメントボーナス', noCommentDetected: '（コメント未検出 — イイネ報酬のみ）', notDetectedYet: 'まだ検出されていません', reconnectNeeded: '再接続が必要です', reconnectMessage: 'YouTubeアクセスを許可するためにサインアウトして再サインインしてください。', tryAgainMessage: '確認が混み合っています。少し待ってから再度請求してください。', accountSuspended: 'アカウントが停止されました', slotTaken: '枠が取られました', slotTakenMessage: '誰かが最後の枠を取りました。別のタスクを試してください！', campaignPaused: 'キャンペーンが一時停止中', campaignPausedMessage: 'このキャンペーンはオーナーにより一時停止されています。', campaignCancelled: 'キャンペーンがキャンセルされました', campaignCancelledMessage: 'このキャンペーンはキャンセルされました。' },
  taskTypes: { subscribe: 'チャンネル登録', like: '動画にイイネ', like_comment: 'イイネ＋コメント', subscribe_like: '登録＋イイネ', watch: '動画を視聴' },
  transactions: { earned: '獲得', spent: '使用', bonus: 'ボーナス' },
  language: { title: '言語', select: '言語を選択', auto: '自動（システム）', changed: '言語を変更しました', changedMsg: 'アプリの言語が更新されました。' },
};

// Korean
export const ko = {
  common: { loading: '로딩 중...', error: '오류', cancel: '취소', save: '저장', confirm: '확인', done: '완료', back: '뒤로', retry: '다시 시도', ok: '확인', yes: '예', no: '아니오', coins: '코인', free: '무료', unlimited: '무제한' },
  tabs: { home: '홈', earn: '적립', boost: '부스트', profile: '프로필', admin: '관리자' },
  splash: { tagline: '함께 성장하기' },
  login: { title: 'Subs Share', tagline: '구독하여 적립하세요.\n사용하여 성장하세요.', feature1: '채널 구독으로 코인 적립', feature2: 'YouTube 인증 — 가짜 작업 없음', feature3: '코인으로 실제 구독자 획득', welcomeBonus: '🎁 50 코인으로 시작하세요!', continueWithGoogle: 'Google로 계속', terms: '구독 및 좋아요 확인을 위해 읽기 전용 YouTube 액세스를 요청합니다.', signInFailed: '로그인 실패', noToken: 'Google에서 토큰을 받지 못했습니다', tryAgain: '다시 시도해 주세요' },
  home: { greeting: '안녕하세요 👋', balance: '내 잔액', coinHint: '10코인 = 구독자 1명', campaigns: '캠페인', pendingSubs: '대기 중인 구독자', completed: '완료됨', quickActions: '빠른 작업', earnCoins: '코인 적립', getSubs: '구독자 얻기', myChannel: '내 채널', activeCampaign: '개 진행 중인 캠페인', activeCampaigns: '개 진행 중인 캠페인', subsPending: '명의 구독자 대기 중', recentActivity: '최근 활동', noTransactions: '아직 거래 내역이 없습니다' },
  earn: { title: '코인 적립하기', subtitle: '작업 완료 · 인증 · 코인 받기', banner: '🔒 구독 및 좋아요는 YouTube에서 인증됩니다.', tierFeatured: '⭐ 추천', tierPremium: '💎 프리미엄', tierCommunity: '📋 커뮤니티', noTasks: '아직 작업이 없습니다', noTasksSubtitle: '나중에 확인하세요', alreadyDone: '✓ 완료', slotsLeft: '개 자리 남음', verifying: 'YouTube로 인증 중...', verifyClaim: '인증 후 받기', pleaseWait: '잠시 기다려 주세요...', readyToVerify: '✅ 인증 준비 완료!', inProgress: '진행 중', keepActive: '타이머 실행 중 작업을 유지하세요', tapToVerify: '아래를 탭하세요 — YouTube로 인증합니다.', secondsRemaining: '초 남음', commentBonus: '💬 댓글을 달았나요? 자동으로 +4 코인을 받게 됩니다!', warningModal: '⚠️ 수령 후 {{action}}을 취소하면 코인이 회수됩니다.', subscription: '구독', like: '좋아요', coinsEarned: '🎉 코인 적립 완료!', balance: '잔액', commentBonusEarned: '💬 댓글 보너스', noCommentDetected: '(댓글 미감지 — 좋아요 보상만 지급)', notDetectedYet: '아직 감지되지 않았습니다', reconnectNeeded: '재연결 필요', reconnectMessage: 'YouTube 액세스 권한을 부여하려면 로그아웃 후 다시 로그인하세요.', tryAgainMessage: '인증이 사용 중입니다. 잠시 후 다시 받기를 탭하세요.', accountSuspended: '계정 정지됨', slotTaken: '자리가 찼습니다', slotTakenMessage: '누군가 마지막 자리를 가져갔습니다. 다른 작업을 시도하세요!', campaignPaused: '캠페인 일시 정지됨', campaignPausedMessage: '이 캠페인은 소유자가 일시 정지했습니다.', campaignCancelled: '캠페인 취소됨', campaignCancelledMessage: '이 캠페인은 취소되었습니다.' },
  taskTypes: { subscribe: '구독하기', like: '동영상 좋아요', like_comment: '좋아요+댓글', subscribe_like: '구독+좋아요', watch: '동영상 시청' },
  transactions: { earned: '적립됨', spent: '사용됨', bonus: '보너스' },
  language: { title: '언어', select: '언어 선택', auto: '자동 (시스템)', changed: '언어 변경됨', changedMsg: '앱 언어가 업데이트되었습니다.' },
};
