// Turkish
export const tr = {
  common: { loading: 'Yükleniyor...', error: 'Hata', cancel: 'İptal', save: 'Kaydet', confirm: 'Onayla', done: 'Tamamlandı', back: 'Geri', retry: 'Tekrar dene', ok: 'Tamam', yes: 'Evet', no: 'Hayır', coins: 'jeton', free: 'Ücretsiz', unlimited: 'Sınırsız' },
  tabs: { home: 'Ana Sayfa', earn: 'Kazan', boost: 'Güçlendir', profile: 'Profil', admin: 'Yönetici' },
  splash: { tagline: 'Birlikte büyüyün' },
  login: { title: 'Subs Share', tagline: 'Kazanmak için abone ol.\nBüyümek için harca.', feature1: 'Kanallara abone olarak jeton kazanın', feature2: 'YouTube tarafından doğrulandı — sahte görev yok', feature3: 'Gerçek abone almak için jeton harcayın', welcomeBonus: '🎁 50 ücretsiz jetonla başlayın!', continueWithGoogle: 'Google ile devam et', terms: 'Aboneliklerinizi ve beğenilerinizi doğrulamak için salt okunur YouTube erişimi talep ediyoruz.', signInFailed: 'Giriş başarısız', noToken: "Google'dan token alınamadı", tryAgain: 'Lütfen tekrar deneyin' },
  home: { greeting: 'İyi günler 👋', balance: 'BAKİYENİZ', coinHint: '10 jeton = 1 abone', campaigns: 'Kampanyalar', pendingSubs: 'Bekleyen aboneler', completed: 'Tamamlandı', quickActions: 'Hızlı işlemler', earnCoins: 'Jeton kazan', getSubs: 'Abone al', myChannel: 'Kanalım', activeCampaign: 'aktif kampanya', activeCampaigns: 'aktif kampanya', subsPending: 'bekleyen abone', recentActivity: 'Son aktivite', noTransactions: 'Henüz işlem yok' },
  earn: { title: 'Jeton Kazan', subtitle: 'Görevler · Doğrulama · Jetonları talep et', banner: '🔒 Abonelikler ve beğeniler YouTube tarafından doğrulanır.', tierFeatured: '⭐ Öne Çıkan', tierPremium: '💎 Premium', tierCommunity: '📋 Topluluk', noTasks: 'Henüz görev yok', noTasksSubtitle: 'Yakında kontrol edin — yeni kampanyalar düzenli olarak ekleniyor', alreadyDone: '✓ Tamamlandı', slotsLeft: 'yer kaldı', verifying: "YouTube ile doğrulanıyor...", verifyClaim: 'Doğrula ve talep et', pleaseWait: 'Lütfen bekleyin...', readyToVerify: '✅ Doğrulamaya hazır!', inProgress: 'devam ediyor', keepActive: 'Zamanlayıcı çalışırken eylemi sürdürün', tapToVerify: "Aşağıya dokunun — YouTube ile doğrulayacağız.", secondsRemaining: 'sn kaldı', commentBonus: '💬 Yorum yaptınız mı? Otomatik olarak +4 jeton alacaksınız!', warningModal: '⚠️ Talep ettikten sonra {{action}} kaldırmak jeton iadesine yol açar.', subscription: 'aboneliğinizi', like: 'beğeninizi', coinsEarned: '🎉 Jetonlar kazanıldı!', balance: 'Bakiye', commentBonusEarned: '💬 Yorum bonusu', noCommentDetected: '(Yorum bulunamadı — yalnızca beğeni ödülü)', notDetectedYet: 'Henüz tespit edilemedi', reconnectNeeded: 'Yeniden bağlantı gerekli', reconnectMessage: 'YouTube erişimi vermek için lütfen çıkış yapıp tekrar girin.', tryAgainMessage: 'Doğrulama meşgul. Bekleyin ve tekrar deneyin.', accountSuspended: 'Hesap askıya alındı', slotTaken: 'Yer alındı', slotTakenMessage: 'Biri son yeri aldı. Başka bir görev deneyin!', campaignPaused: 'Kampanya duraklatıldı', campaignPausedMessage: 'Bu kampanya sahip tarafından duraklatıldı.', campaignCancelled: 'Kampanya iptal edildi', campaignCancelledMessage: 'Bu kampanya iptal edildi.' },
  taskTypes: { subscribe: 'Abone ol', like: 'Videoyu beğen', like_comment: 'Beğen + Yorum yap', subscribe_like: 'Abone ol + Beğen', watch: 'Video izle' },
  transactions: { earned: 'Kazanıldı', spent: 'Harcandı', bonus: 'Bonus' },
  language: { title: 'Dil', select: 'Dil seçin', auto: 'Otomatik (Sistem)', changed: 'Dil değiştirildi', changedMsg: 'Uygulama dili güncellendi.' },
};

// Indonesian
export const id = {
  common: { loading: 'Memuat...', error: 'Kesalahan', cancel: 'Batal', save: 'Simpan', confirm: 'Konfirmasi', done: 'Selesai', back: 'Kembali', retry: 'Coba lagi', ok: 'OK', yes: 'Ya', no: 'Tidak', coins: 'koin', free: 'Gratis', unlimited: 'Tak terbatas' },
  tabs: { home: 'Beranda', earn: 'Hasilkan', boost: 'Tingkatkan', profile: 'Profil', admin: 'Admin' },
  splash: { tagline: 'Tumbuh bersama' },
  login: { title: 'Subs Share', tagline: 'Berlangganan untuk menghasilkan.\nBelanjakan untuk berkembang.', feature1: 'Hasilkan koin dengan berlangganan saluran', feature2: 'Diverifikasi oleh YouTube — tidak ada tugas palsu', feature3: 'Belanjakan koin untuk mendapatkan pelanggan nyata', welcomeBonus: '🎁 Mulai dengan 50 koin gratis!', continueWithGoogle: 'Lanjutkan dengan Google', terms: 'Kami meminta akses YouTube hanya-baca untuk memverifikasi langganan dan suka Anda.', signInFailed: 'Gagal masuk', noToken: 'Tidak ada token dari Google', tryAgain: 'Silakan coba lagi' },
  home: { greeting: 'Halo 👋', balance: 'SALDO ANDA', coinHint: '10 koin = 1 pelanggan', campaigns: 'Kampanye', pendingSubs: 'Pelanggan tertunda', completed: 'Selesai', quickActions: 'Tindakan cepat', earnCoins: 'Hasilkan koin', getSubs: 'Dapatkan pelanggan', myChannel: 'Saluran saya', activeCampaign: 'kampanye aktif', activeCampaigns: 'kampanye aktif', subsPending: 'pelanggan tertunda', recentActivity: 'Aktivitas terkini', noTransactions: 'Belum ada transaksi' },
  earn: { title: 'Hasilkan Koin', subtitle: 'Tugas · Terverifikasi · Klaim koin', banner: '🔒 Langganan dan suka diverifikasi oleh YouTube.', tierFeatured: '⭐ Unggulan', tierPremium: '💎 Premium', tierCommunity: '📋 Komunitas', noTasks: 'Belum ada tugas', noTasksSubtitle: 'Periksa lagi nanti — kampanye baru ditambahkan secara rutin', alreadyDone: '✓ Selesai', slotsLeft: 'slot tersisa', verifying: 'Memverifikasi dengan YouTube...', verifyClaim: 'Verifikasi & Klaim', pleaseWait: 'Harap tunggu...', readyToVerify: '✅ Siap diverifikasi!', inProgress: 'sedang berlangsung', keepActive: 'Pertahankan tindakan selama timer berjalan', tapToVerify: 'Ketuk di bawah — kami akan memverifikasi dengan YouTube.', secondsRemaining: 'dtk tersisa', commentBonus: '💬 Berkomentar? Anda akan otomatis mendapat +4 koin!', warningModal: '⚠️ Menghapus {{action}} setelah klaim akan mengakibatkan koin dikembalikan.', subscription: 'langganan', like: 'suka', coinsEarned: '🎉 Koin berhasil diperoleh!', balance: 'Saldo', commentBonusEarned: '💬 Bonus komentar', noCommentDetected: '(Tidak ada komentar terdeteksi — hanya hadiah suka)', notDetectedYet: 'Belum terdeteksi', reconnectNeeded: 'Perlu hubungkan ulang', reconnectMessage: 'Silakan keluar dan masuk kembali untuk memberi akses YouTube.', tryAgainMessage: 'Verifikasi sibuk. Tunggu sebentar lalu coba klaim lagi.', accountSuspended: 'Akun ditangguhkan', slotTaken: 'Slot diambil', slotTakenMessage: 'Seseorang baru saja mengambil slot terakhir. Coba tugas lain!', campaignPaused: 'Kampanye dijeda', campaignPausedMessage: 'Kampanye ini dijeda oleh pemilik. Coba tugas lain.', campaignCancelled: 'Kampanye dibatalkan', campaignCancelledMessage: 'Kampanye ini dibatalkan. Coba tugas lain.' },
  taskTypes: { subscribe: 'Berlangganan', like: 'Suka video', like_comment: 'Suka + Komentar', subscribe_like: 'Berlangganan + Suka', watch: 'Tonton video' },
  transactions: { earned: 'Diperoleh', spent: 'Dibelanjakan', bonus: 'Bonus' },
  language: { title: 'Bahasa', select: 'Pilih bahasa', auto: 'Otomatis (Sistem)', changed: 'Bahasa diubah', changedMsg: 'Bahasa aplikasi telah diperbarui.' },
};

// Hindi
export const hi = {
  common: { loading: 'लोड हो रहा है...', error: 'त्रुटि', cancel: 'रद्द करें', save: 'सहेजें', confirm: 'पुष्टि करें', done: 'हो गया', back: 'वापस', retry: 'फिर कोशिश करें', ok: 'ठीक है', yes: 'हाँ', no: 'नहीं', coins: 'सिक्के', free: 'मुफ़्त', unlimited: 'असीमित' },
  tabs: { home: 'होम', earn: 'कमाएं', boost: 'बूस्ट', profile: 'प्रोफाइल', admin: 'एडमिन' },
  splash: { tagline: 'मिलकर बढ़ें' },
  login: { title: 'Subs Share', tagline: 'कमाने के लिए सब्सक्राइब करें।\nबढ़ने के लिए खर्च करें।', feature1: 'चैनल्स को सब्सक्राइब करके सिक्के कमाएं', feature2: 'YouTube द्वारा सत्यापित — कोई फर्जी कार्य नहीं', feature3: 'असली सब्सक्राइबर पाने के लिए सिक्के खर्च करें', welcomeBonus: '🎁 50 मुफ्त सिक्कों से शुरुआत करें!', continueWithGoogle: 'Google से जारी रखें', terms: 'हम आपकी सदस्यता और लाइक की पुष्टि के लिए YouTube तक केवल-पढ़ने की पहुंच मांगते हैं।', signInFailed: 'साइन इन विफल', noToken: 'Google से कोई टोकन नहीं मिला', tryAgain: 'कृपया दोबारा कोशिश करें' },
  home: { greeting: 'नमस्ते 👋', balance: 'आपका बैलेंस', coinHint: '10 सिक्के = 1 सब्सक्राइबर', campaigns: 'अभियान', pendingSubs: 'प्रतीक्षित सब्सक्राइबर', completed: 'पूर्ण', quickActions: 'त्वरित क्रियाएं', earnCoins: 'सिक्के कमाएं', getSubs: 'सब्सक्राइबर पाएं', myChannel: 'मेरा चैनल', activeCampaign: 'सक्रिय अभियान', activeCampaigns: 'सक्रिय अभियान', subsPending: 'सब्सक्राइबर प्रतीक्षित', recentActivity: 'हाल की गतिविधि', noTransactions: 'अभी तक कोई लेनदेन नहीं' },
  earn: { title: 'सिक्के कमाएं', subtitle: 'कार्य · सत्यापित · सिक्के प्राप्त करें', banner: '🔒 सदस्यता और लाइक YouTube द्वारा सत्यापित हैं।', tierFeatured: '⭐ फीचर्ड', tierPremium: '💎 प्रीमियम', tierCommunity: '📋 समुदाय', noTasks: 'अभी कोई कार्य नहीं', noTasksSubtitle: 'जल्द वापस देखें — नए अभियान नियमित रूप से जोड़े जाते हैं', alreadyDone: '✓ हो गया', slotsLeft: 'स्लॉट बचे हैं', verifying: 'YouTube से सत्यापित हो रहा है...', verifyClaim: 'सत्यापित करें और प्राप्त करें', pleaseWait: 'कृपया प्रतीक्षा करें...', readyToVerify: '✅ सत्यापन के लिए तैयार!', inProgress: 'जारी है', keepActive: 'टाइमर चलते समय क्रिया बनाए रखें', tapToVerify: 'नीचे टैप करें — हम YouTube से सत्यापित करेंगे।', secondsRemaining: 'सेकंड शेष', commentBonus: '💬 कमेंट किया? आपको स्वचालित रूप से +4 सिक्के मिलेंगे!', warningModal: '⚠️ दावे के बाद {{action}} हटाने से सिक्के वापस लिए जाएंगे।', subscription: 'सदस्यता', like: 'लाइक', coinsEarned: '🎉 सिक्के कमाए!', balance: 'बैलेंस', commentBonusEarned: '💬 कमेंट बोनस', noCommentDetected: '(कोई कमेंट नहीं मिला — केवल लाइक पुरस्कार)', notDetectedYet: 'अभी तक नहीं मिला', reconnectNeeded: 'पुनः कनेक्ट आवश्यक', reconnectMessage: 'YouTube एक्सेस देने के लिए कृपया साइन आउट करें और फिर साइन इन करें।', tryAgainMessage: 'सत्यापन व्यस्त है। थोड़ा रुकें और फिर दावा करें।', accountSuspended: 'खाता निलंबित', slotTaken: 'स्लॉट लिया गया', slotTakenMessage: 'किसी ने आखिरी स्लॉट ले लिया। दूसरा कार्य आज़माएं!', campaignPaused: 'अभियान रुका हुआ', campaignPausedMessage: 'यह अभियान मालिक द्वारा रोका गया है।', campaignCancelled: 'अभियान रद्द', campaignCancelledMessage: 'यह अभियान रद्द कर दिया गया है।' },
  taskTypes: { subscribe: 'सब्सक्राइब करें', like: 'वीडियो लाइक करें', like_comment: 'लाइक + कमेंट', subscribe_like: 'सब्सक्राइब + लाइक', watch: 'वीडियो देखें' },
  transactions: { earned: 'कमाया', spent: 'खर्च किया', bonus: 'बोनस' },
  language: { title: 'भाषा', select: 'भाषा चुनें', auto: 'स्वचालित (सिस्टम)', changed: 'भाषा बदली', changedMsg: 'ऐप की भाषा अपडेट की गई।' },
};

// Russian
export const ru = {
  common: { loading: 'Загрузка...', error: 'Ошибка', cancel: 'Отмена', save: 'Сохранить', confirm: 'Подтвердить', done: 'Готово', back: 'Назад', retry: 'Повторить', ok: 'ОК', yes: 'Да', no: 'Нет', coins: 'монеты', free: 'Бесплатно', unlimited: 'Безлимитно' },
  tabs: { home: 'Главная', earn: 'Заработок', boost: 'Буст', profile: 'Профиль', admin: 'Админ' },
  splash: { tagline: 'Расти вместе' },
  login: { title: 'Subs Share', tagline: 'Подписывайся и зарабатывай.\nТрать и расти.', feature1: 'Зарабатывай монеты, подписываясь на каналы', feature2: 'Верифицировано YouTube — без фейковых задач', feature3: 'Трать монеты для получения реальных подписчиков', welcomeBonus: '🎁 Начни с 50 бесплатных монет!', continueWithGoogle: 'Продолжить с Google', terms: 'Мы запрашиваем доступ к YouTube только для чтения для верификации ваших подписок и лайков.', signInFailed: 'Ошибка входа', noToken: 'Токен от Google не получен', tryAgain: 'Пожалуйста, попробуйте снова' },
  home: { greeting: 'Добрый день 👋', balance: 'ВАШ БАЛАНС', coinHint: '10 монет = 1 подписчик', campaigns: 'Кампании', pendingSubs: 'Ожидающие подписчики', completed: 'Завершено', quickActions: 'Быстрые действия', earnCoins: 'Заработать монеты', getSubs: 'Получить подписчиков', myChannel: 'Мой канал', activeCampaign: 'активная кампания', activeCampaigns: 'активные кампании', subsPending: 'подписчики ожидают', recentActivity: 'Недавняя активность', noTransactions: 'Транзакций пока нет' },
  earn: { title: 'Заработать монеты', subtitle: 'Задачи · Верификация · Получить монеты', banner: '🔒 Подписки и лайки верифицируются YouTube.', tierFeatured: '⭐ Рекомендуемое', tierPremium: '💎 Премиум', tierCommunity: '📋 Сообщество', noTasks: 'Задач пока нет', noTasksSubtitle: 'Заходи позже — новые кампании добавляются регулярно', alreadyDone: '✓ Готово', slotsLeft: 'мест осталось', verifying: 'Верификация через YouTube...', verifyClaim: 'Верифицировать и получить', pleaseWait: 'Пожалуйста, подождите...', readyToVerify: '✅ Готово к верификации!', inProgress: 'в процессе', keepActive: 'Держите действие активным пока идёт таймер', tapToVerify: 'Нажмите ниже — мы верифицируем через YouTube.', secondsRemaining: 'сек осталось', commentBonus: '💬 Оставили комментарий? Вы автоматически получите +4 монеты!', warningModal: '⚠️ Удаление {{action}} после получения приведёт к возврату монет.', subscription: 'подписку', like: 'лайк', coinsEarned: '🎉 Монеты заработаны!', balance: 'Баланс', commentBonusEarned: '💬 Бонус за комментарий', noCommentDetected: '(Комментарий не найден — только награда за лайк)', notDetectedYet: 'Ещё не обнаружено', reconnectNeeded: 'Требуется переподключение', reconnectMessage: 'Пожалуйста, выйдите и войдите снова для предоставления доступа к YouTube.', tryAgainMessage: 'Верификация занята. Подождите и попробуйте снова.', accountSuspended: 'Аккаунт заблокирован', slotTaken: 'Место занято', slotTakenMessage: 'Кто-то занял последнее место. Попробуйте другую задачу!', campaignPaused: 'Кампания на паузе', campaignPausedMessage: 'Эта кампания приостановлена владельцем.', campaignCancelled: 'Кампания отменена', campaignCancelledMessage: 'Эта кампания была отменена.' },
  taskTypes: { subscribe: 'Подписаться', like: 'Лайкнуть видео', like_comment: 'Лайк + Комментарий', subscribe_like: 'Подписаться + Лайк', watch: 'Посмотреть видео' },
  transactions: { earned: 'Заработано', spent: 'Потрачено', bonus: 'Бонус' },
  language: { title: 'Язык', select: 'Выбрать язык', auto: 'Авто (Система)', changed: 'Язык изменён', changedMsg: 'Язык приложения был обновлён.' },
};

// German
export const de = {
  common: { loading: 'Laden...', error: 'Fehler', cancel: 'Abbrechen', save: 'Speichern', confirm: 'Bestätigen', done: 'Fertig', back: 'Zurück', retry: 'Erneut versuchen', ok: 'OK', yes: 'Ja', no: 'Nein', coins: 'Münzen', free: 'Kostenlos', unlimited: 'Unbegrenzt' },
  tabs: { home: 'Start', earn: 'Verdienen', boost: 'Boost', profile: 'Profil', admin: 'Admin' },
  splash: { tagline: 'Gemeinsam wachsen' },
  login: { title: 'Subs Share', tagline: 'Abonnieren um zu verdienen.\nAusgeben um zu wachsen.', feature1: 'Verdiene Münzen durch das Abonnieren von Kanälen', feature2: 'Von YouTube verifiziert — keine falschen Aufgaben', feature3: 'Gib Münzen aus, um echte Abonnenten zu bekommen', welcomeBonus: '🎁 Starte mit 50 kostenlosen Münzen!', continueWithGoogle: 'Mit Google fortfahren', terms: 'Wir fordern schreibgeschützten YouTube-Zugriff zur Verifizierung deiner Abonnements und Likes an.', signInFailed: 'Anmeldung fehlgeschlagen', noToken: 'Kein Token von Google erhalten', tryAgain: 'Bitte versuche es erneut' },
  home: { greeting: 'Guten Tag 👋', balance: 'DEIN GUTHABEN', coinHint: '10 Münzen = 1 Abonnent', campaigns: 'Kampagnen', pendingSubs: 'Ausstehende Abonnenten', completed: 'Abgeschlossen', quickActions: 'Schnellaktionen', earnCoins: 'Münzen verdienen', getSubs: 'Abonnenten bekommen', myChannel: 'Mein Kanal', activeCampaign: 'aktive Kampagne', activeCampaigns: 'aktive Kampagnen', subsPending: 'Abonnenten ausstehend', recentActivity: 'Letzte Aktivitäten', noTransactions: 'Noch keine Transaktionen' },
  earn: { title: 'Münzen verdienen', subtitle: 'Aufgaben · Verifiziert · Münzen beanspruchen', banner: '🔒 Abonnements und Likes werden von YouTube verifiziert.', tierFeatured: '⭐ Empfohlen', tierPremium: '💎 Premium', tierCommunity: '📋 Community', noTasks: 'Noch keine Aufgaben', noTasksSubtitle: 'Schau bald wieder vorbei — neue Kampagnen werden regelmäßig hinzugefügt', alreadyDone: '✓ Erledigt', slotsLeft: 'Plätze übrig', verifying: 'Wird mit YouTube verifiziert...', verifyClaim: 'Verifizieren & beanspruchen', pleaseWait: 'Bitte warten...', readyToVerify: '✅ Bereit zur Verifizierung!', inProgress: 'läuft', keepActive: 'Halte die Aktion aufrecht während der Timer läuft', tapToVerify: 'Tippe unten — wir verifizieren mit YouTube.', secondsRemaining: 'Sek. verbleibend', commentBonus: '💬 Kommentiert? Du erhältst automatisch +4 Münzen!', warningModal: '⚠️ Das Entfernen deines {{action}} nach dem Beanspruchen führt zur Rückforderung der Münzen.', subscription: 'Abonnements', like: 'Likes', coinsEarned: '🎉 Münzen verdient!', balance: 'Guthaben', commentBonusEarned: '💬 Kommentarbonus', noCommentDetected: '(Kein Kommentar erkannt — nur Like-Belohnung)', notDetectedYet: 'Noch nicht erkannt', reconnectNeeded: 'Neuverbindung erforderlich', reconnectMessage: 'Bitte melde dich ab und erneut an, um YouTube-Zugriff zu gewähren.', tryAgainMessage: 'Verifizierung beschäftigt. Warte einen Moment und versuche es erneut.', accountSuspended: 'Konto gesperrt', slotTaken: 'Platz vergeben', slotTakenMessage: 'Jemand hat den letzten Platz genommen. Versuche eine andere Aufgabe!', campaignPaused: 'Kampagne pausiert', campaignPausedMessage: 'Diese Kampagne wurde vom Besitzer pausiert.', campaignCancelled: 'Kampagne abgebrochen', campaignCancelledMessage: 'Diese Kampagne wurde abgebrochen.' },
  taskTypes: { subscribe: 'Abonnieren', like: 'Video liken', like_comment: 'Liken + Kommentieren', subscribe_like: 'Abonnieren + Liken', watch: 'Video anschauen' },
  transactions: { earned: 'Verdient', spent: 'Ausgegeben', bonus: 'Bonus' },
  language: { title: 'Sprache', select: 'Sprache wählen', auto: 'Auto (System)', changed: 'Sprache geändert', changedMsg: 'Die App-Sprache wurde aktualisiert.' },
};
